### PR TITLE
Updating conflicting LICENSE file

### PR DESCRIPTION
**Pull request by jprafael**
This repository had conflicting versions of the GPL.
 * The `LICENSE` file contained the GPLv2.
 * The `pom.xml` and all `*.java` file headers mention GPLv3.

Updating to GPLv3 looks like the right thing to do here.

### CODE REVIEW

**Comment by defer** [comment]
It should be GPLv2 because Weka 3.6.x is distributed under that license.

**Comment by jprafael** [comment]
In that case there is a different problem. The [fos-core](https://github.com/feedzai/fos-core) repository is dual licensed as GPLv3 and Apache. According to [apache.org](http://www.apache.org/licenses/GPL-compatibility.html) its not clear if the latter is compatible with GPLv2.

**Comment by defer** [comment]
It is in the sense that merging a gplv2 project with an Apache project will result in a gplv2 project.

Weka 3.7 is GPL v3, upgrading might be possible. 

Another, less confusing option would be to relicense fos core as Gplv2 or later and Apache.

**Comment by defer** [comment]
It is in the sense that merging a gplv2 project with an Apache project will result in a gplv2 project.

Weka 3.7 is GPL v3, upgrading might be possible. 

Another, less confusing option would be to relicense fos core as Gplv2 or later and Apache.

**Comment by jprafael** [comment]
Upgrading might be an option. FastRandomForest is GPLv2+, and their latest version already uses Weka 3.7. The problem with this upgrade is that the FRF 0.99 (latest) implementation has a substantially different algorithm (versus 0.98) and will yield different results.

**Comment by jprafael** [comment]
I messed up. Didn't knew that GitHub pull requests actually track the branch and not the commit. Closing this PR as it now contains more changes than it should.

**Pull request closed without merging**
